version: '3'
services:
  frontend:
    build:
      context: ./frontend-service
    ports:
      - '3000:3000'
    networks:
      - backend

  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - '8080:8080'
    networks:
      - backend

  movie-actor-service:
    build:
      context: ./movie-service
    ports:
      - '8001:8001'
    networks:
      - backend
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/movies_db?useSSL=false&serverTimezone=Europe/Madrid&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpassword

  auth-user-service:
    build:
      context: ./user-service
    ports:
      - '8002:8002'
    networks:
      - backend
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/movies_db?useSSL=false&serverTimezone=Europe/Madrid&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpassword

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '80:80'
    networks:
      - backend

  mysql-db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: movies_db
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - '3307:3306'
    networks:
      - backend
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d

  gitlab:
    image: gitlab/gitlab-ce:latest
    restart: always
    hostname: gitlab
    ports:
      - '8929:8929'
    networks:
      - backend
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost:8929'
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab

  portainer:
    image: portainer/portainer-ce:latest
    restart: always
    ports:
      - '9000:9000'
    networks:
      - backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data

networks:
  backend:
    driver: bridge

volumes:
  mysql-data:
  gitlab-config:
  gitlab-logs:
  gitlab-data:
  portainer-data:
